<a href="https://colab.research.google.com/github/guilhermelaviola/AtividadesDescomplica/blob/main/Atividade1_Pr%C3%A1ticaIntegradoraDeCi%C3%AAnciaDeDadosComCloudComputing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividade

Nesta atividade, vamos praticar Python com a biblioteca NumPy, com comandos básicos. É importante que você faça isso com muita tranquilidade e siga todos os passos.

A atividade parece extensa, pela quantidade de passos, mas não se assuste! Um bom programador deve saber que quanto mais passos, melhor pode ficar seu sistema!

In [1]:
# Importando a biblioteca NumPy.
import numpy as np

In [19]:
# Criando um array unidimensional chamado arr com os números de 1 a 10.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [22]:
# Criando uma matriz bidimensional chamada matriz com dimensões 3x4, preenchida com números inteiros de 1 a 12.
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [23]:
# Imprimindo o array arr e a matriz matriz.
print('Array: ', arr)
print('Matriz:', matriz)

Array:  [ 1  2  3  4  5  6  7  8  9 10]
Matriz: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
# Acessando o elemento “5” do array arr e o elemento “8” da matriz matriz e imprimindo os valores obtidos.
el5 = arr[5]
el8 = matriz[2:3]

print('Elemento 5 do array:', el5)
print('Elemento 8 da matriz:', el8)

Elemento 5 do array: 6
Elemento 8 da matriz: [[7 8 9]]
