<a href="https://colab.research.google.com/github/guilhermelaviola/AtividadesDescomplica/blob/main/Atividade1_Pr%C3%A1ticaIntegradoraDeCi%C3%AAnciaDeDadosComCloudComputing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividade

Nesta atividade, vamos praticar Python com a biblioteca NumPy, com comandos básicos. É importante que você faça isso com muita tranquilidade e siga todos os passos.

A atividade parece extensa, pela quantidade de passos, mas não se assuste! Um bom programador deve saber que quanto mais passos, melhor pode ficar seu sistema!

In [1]:
# Importando a biblioteca NumPy.
import numpy as np

In [28]:
# Criando um array unidimensional chamado arr com os números de 1 a 10 e imprimindo o array:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [29]:
# Criando uma matriz bidimensional chamada matriz com dimensões 3x4, preenchida com números inteiros de 1 a 12 e impriminfo a matriz:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [31]:
# Imprimindo o array arr e a matriz matriz:
print('Array arr: ', arr)
print('Matriz matriz:', matriz)

Array arr:  [ 1  2  3  4  5  6  7  8  9 10]
Matriz matriz: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [47]:
# Acessando o elemento “5” do array arr e o elemento “8” da matriz matriz e imprimindo os valores obtidos:
el5 = arr[5]
el8 = matriz[2:3]

print('Elemento 5 do array:', el5)
print('Elemento 8 da matriz:', el8)

Elemento 5 do array: 6
Elemento 8 da matriz: [[7 8 9]]


In [49]:
# Criando um novo array chamado arr_slice que contenha os elementos do array arr no intervalo de índices de 2 a 6 (exclusivo) e imprimindo o array:
arr_slice = arr[2:6]
print('arr_slice', arr_slice)

arr_slice [3 4 5 6]


In [52]:
# Realizando uma operação matemática de sua escolha (por exemplo, multiplicação por 2) em todos os elementos do array arr e armazenando o resultado em um novo array chamado arr_resultado e imprimindo o valor obtido:
arr_resultado = arr * 2
print('Multiplicação por 2:',arr_resultado)

Multiplicação por 2: [ 2  4  6  8 10 12 14 16 18 20]


In [54]:
# Calculando a soma de todos os elementos da matriz matriz e imprimindo o valor obtido.
soma = np.sum(matriz)
print('Soma dos valores:', soma)

Soma dos valores: 78


In [55]:
# Calculando a média dos elementos do array arr e imprimindo o valor obtido.
arr_mean = np.mean(arr)
print('Média dos elementos:', arr_mean)

Média dos elementos: 5.5


In [57]:
# Criando uma matriz chamada matriz_transposta que seja a transposta da matriz "matriz", e imprimindo a matriz matriz_transposta.
matriz_transposta = matriz.T
print('Matriz transposta:', matriz_transposta)

Matriz transposta: [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [58]:
# Concatenando o array arr com o array arr_slice e armazene o resultado em um novo array chamado arr_concatenado imprimindo o array arr_concatenado.
arr_concatenado = np.concatenate((arr, arr_slice), axis=0)
print('Array concatenado:', arr_concatenado)

Array concatenado: [ 1  2  3  4  5  6  7  8  9 10  3  4  5  6]
